// Generated by CoffeeScript 1.7.1
(function() {
  var Window,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Window = (function() {
    function Window() {
      this.setContent = __bind(this.setContent, this);
      this.show = __bind(this.show, this);
      this.el = document.createElement('div');
      this.el.classList.add('window');
      this.size = [220, 30];
    }

    Window.prototype.show = function(pos) {
      this.el.style.left = pos[0] + "px";
      this.el.style.top = pos[1] + "px";
      return document.body.appendChild(this.el);
    };

    Window.prototype.setContent = function(content) {
      return this.el.innerHTML = "<p>" + content + "</p>";
    };

    return Window;

  })();

  module.exports = Window;

}).call(this);
